Repository govCMS/lagoon, pull requests merged in 2020-04, with the labels that each got.

#136 [GOVCMS-3219] Fixes inability to disable dev mode outside of production.
  .docker/images/govcms8/settings/settings.php
Labels: Needs review

#129 [GOVCMS-2677]: Nginx Security headers
  .docker/images/nginx/helpers/207-seucirty-headers.conf
  .docker/images/nginx/tests/src/SecurityHeadersTest.php
Labels: Needs review

#122 Replaced CI runner image with govcms/govcms-ci.
  .circleci/config.yml
Labels: DO NOT MERGE, Requires more work

#135 Added override for temporary file deletion.
  .docker/images/govcms8/settings/production.settings.php
Labels: Ready to be merged

#151 Fixed added replicas in databases array.
  .docker/images/govcms8/settings/settings.php
Labels: Needs review
